--CREATE DATABASE EventBaseBooking;

use EventBaseBooking;

DROP TABLE Bookings;
DROP TABLE Events;
DROP TABLE Venues;
DROP TABLE Specialists;

CREATE TABLE Specialists(
SpecialistID INT IDENTITY(1,1) PRIMARY KEY,
SpecialistName NVARCHAR(200) NOT NULL,
SpecialistEmail NVARCHAR (200) NOT NULL
);

CREATE TABLE Venues(
VenueID INT IDENTITY (1,1) PRIMARY KEY,
VenueName NVARCHAR(200) NOT NULL,
VenueLocation NVARCHAR(200) NOT NULL,
Capacity INT NOT NULL

);

CREATE TABLE Events(
	EventID INT IDENTITY(1,1) PRIMARY KEY,
	EventName NVARCHAR(100) NOT NULL,
	EventStartDate DATETIME NOT NULL,
	EventEndtDate DATETIME NOT NULL

);

CREATE TABLE Bookings(

BookingID INT IDENTITY(1,1) PRIMARY KEY,
SpecialistID INT NOT NULL,
VenueID INT NOT NULL,
EventID INT NOT NULL,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL,

CONSTRAINT FK_Specialists
FOREIGN KEY (SpecialistID)
REFERENCES Specialists(SpecialistID)
ON DELETE CASCADE,

CONSTRAINT FK_Booking_Venues
FOREIGN KEY (VenueID)
REFERENCES Venues(VenueID)
ON DELETE CASCADE,

CONSTRAINT FK_Booking_Events
FOREIGN KEY (EventID)
REFERENCES Events(EventID)
ON DELETE CASCADE

);
