// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cldv_Poe_Submission.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int EventId { get; set; }

    public string SpecialistName { get; set; }

    public string SpecialistEmail { get; set; }

    public DateTime BookingDate { get; set; }

    public int VenueId { get; set; }

    public virtual Event Event { get; set; }

    public virtual Venue Venue { get; set; }
}