// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cldv_Poe_Submission.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int EventId { get; set; }

    [Display(Name = "Specialist Name")]
    public string SpecialistName { get; set; }

    [Display(Name = "Specialist Email")]
    public string SpecialistEmail { get; set; }

    [Display(Name = "Booking Date")]
    public DateTime BookingDate { get; set; }

    public int VenueId { get; set; }

    public virtual Event Event { get; set; }

    public virtual Venue Venue { get; set; }
}