// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cldv_Poe_Submission.Models;

public partial class Event
{
    public int EventId { get; set; }

    [Display(Name = "Event Name")]
    public string EventName { get; set; }

    [Display(Name = "Start Date")]
    public DateTime StartDate { get; set; }

    [Display(Name = "End Date")]
    public DateTime EndDate { get; set; }

    [Display(Name = "Event Description")]
    public string EventDescription { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}