// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cldv_Poe_Submission.Models;

public partial class Event
{
    public int EventId { get; set; }

    public string EventName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string EventDescription { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}