// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cldv_Poe_Submission.Models;

public partial class EventType
{
    public int EventTypeId { get; set; }

    public string EventTypes { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}