// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cldv_Poe_Submission.Models;

public partial class Specialist
{
    public int SpecialistId { get; set; }

    public string SpecialistName { get; set; }

    public string SpecialistEmail { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}