// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cldv_Poe_Submission.Models;

public partial class Venue
{
    public int VenueId { get; set; }

    public string VenueName { get; set; }

    public string VenueLocation { get; set; }

    public int Capacity { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}